<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\LoginHandler::class => App\Handler\LoginHandlerFactory::class,
            App\Handler\OauthHandler::class => App\Handler\OauthHandlerFactory::class,
            App\Handler\OauthSocialHandler::class => App\Handler\OauthSocialHandlerFactory::class,
            App\Handler\VersionHandler::class => App\Handler\VersionHandlerFactory::class,
            App\Middleware\CorsManagerMiddleware::class => App\Middleware\CorsManagerMiddlewareFactory::class,
        ],
    ],
];
